### Rss Get All

GET {{host}}/Rss

### Rss Get Json (Request format)

GET {{host}}/Rss/Json/All

### Rss Get Json Category

GET {{host}}/Rss/Json?category=개인

### Rss Get Error

GET {{host}}/Rss/Error

### Rss Create Multi

POST {{host}}/Rss/Multi
Content-Type: application/json

{
	"Datas": [
    {
      "url": "https://ppss.kr/archives/category/it/rss",
      "name": "ㅍㅍㅅㅅ",
      "category": "큐레이팅",
    },
    {
      "url": "https://devblogs.microsoft.com/cppblog/feed/",
      "name": "C++ Team Blog",
      "category": "기업"
    },
    {
      "url": "https://code.facebook.com/posts/rss",
      "name": "Facebook Engineering",
      "category": "기업"
    },
    {
      "url": "http://www.ebaytechblog.com/feed/",
      "name": "eBay Tech Blog",
      "category": "기업"
    },
    {
      "url": "http://feeds.feedburner.com/TwitterBlog",
      "name": "Twitter Blog",
      "category": "기업"
    },
    {
      "url": "https://medium.com/feed/netflix-techblog",
      "name": "Netflix TechBlog",
      "category": "기업"
    },
    {
      "url": "https://blog.jetbrains.com/feed/",
      "name": "JetBrains: Developer Tools for Professionals and Teams – Company Blog | JetBrains",
      "category": "기업"
    },
    {
      "url": "https://engineering.linkedin.com/blog.rss",
      "name": "LinkedIn Engineering",
      "category": "기업"
    },
    {
      "url": "https://medium.com/feed/airbnb-engineering",
      "name": "Airbnb Engineering & Data Science",
      "category": "기업"
    },
    {
      "url": "https://developer.amazon.com/blogs/home/feed/entries/atom",
      "name": "Amazon Developer Blogs",
      "category": "기업"
    },
    {
      "url": "http://instagram-engineering.tumblr.com/rss",
      "name": "Instagram Engineering",
      "category": "기업"
    },
    {
      "url": "https://medium.com/feed/paypal-engineering",
      "name": "PayPal Engineering",
      "category": "기업"
    },
    {
      "url": "https://techcommunity.microsoft.com/gxcuf89792/rss/message?board.id=PlannerBlog&message.id=200",
      "name": "article New updates to Planner comment notifications and settings in Planner Blog",
      "category": "기업"
    },
    {
      "url": "https://devblogs.microsoft.com/visualstudio/feed/",
      "name": "Visual Studio Blog",
      "category": "기업"
    },
    {
      "url": "https://instagram-engineering.com/feed",
      "name": "Instagram Engineering",
      "category": "기업"
    },
    {
      "url": "https://blogs.dropbox.com/tech/feed/",
      "name": "Dropbox Tech Blog",
      "category": "기업"
    },
    {
      "url": "https://joshua1988.github.io/atom.xml",
      "name": "Joshua",
      "category": "개인"
    },
    {
      "url": "http://dataninja.me/feed.xml",
      "name": "권재명",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@ERG",
      "name": "김석기",
      "category": "개인"
    },
    {
      "url": "http://sunyzero.tistory.com/rss",
      "name": "김선영",
      "category": "개인"
    },
    {
      "url": "http://jinhokwon.tistory.com/rss",
      "name": "권진호",
      "category": "개인"
    },
    {
      "url": "http://charsyam.wordpress.com/feed/",
      "name": "강대명",
      "category": "개인"
    },
    {
      "url": "http://xguru.net/feed",
      "name": "권정혁",
      "category": "개인"
    },
    {
      "url": "https://wckhg89.github.io/feed.xml",
      "name": "줌구",
      "category": "개인"
    },
    {
      "url": "http://nolsigan.github.io/feed.xml",
      "name": "김범준",
      "category": "개인"
    },
    {
      "url": "https://subokim.wordpress.com/feed/",
      "name": "김수보",
      "category": "개인"
    },
    {
      "url": "http://rss.egloos.com/blog/himskim",
      "name": "김명신",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@2MrI",
      "name": "김시은",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@YZF",
      "name": "곽민수",
      "category": "개인"
    },
    {
      "url": "https://medium.com/feed/@beejei",
      "name": "김범진",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/mseokim011117.xml",
      "name": "김민서",
      "category": "개인"
    },
    {
      "url": "https://iamnotokay.tistory.com/rss",
      "name": "I am not Okay",
      "category": "개인"
    },
    {
      "url": "http://thoughts.chkwon.net/feed/",
      "name": "권창현",
      "category": "개인"
    },
    {
      "url": "http://kwongyo.tistory.com/rss",
      "name": "권기호",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@PUo",
      "name": "김수민",
      "category": "개인"
    },
    {
      "url": "http://daddynkidsmakers.blogspot.com/feeds/posts/default",
      "name": "강태욱",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@H9i",
      "name": "권용진",
      "category": "개인"
    },
    {
      "url": "https://nesoy.github.io/atom.xml",
      "name": "권영재",
      "category": "개인"
    },
    {
      "url": "http://alwayspr.tistory.com/rss",
      "name": "김민수",
      "category": "개인"
    },
    {
      "url": "http://raccoonyy.github.io/rss",
      "name": "김승호",
      "category": "개인"
    },
    {
      "url": "http://kimbyeonghwan.tumblr.com/rss",
      "name": "김병환",
      "category": "개인"
    },
    {
      "url": "https://rss.blog.naver.com/boyism.xml",
      "name": "RSS feed for boyism Blog",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@20dR",
      "name": "김성준의 린스타트업과 디자인씽킹",
      "category": "개인"
    },
    {
      "url": "https://medium.com/feed/@khwsc1",
      "name": "권혁우",
      "category": "개인"
    },
    {
      "url": "https://medium.com/feed/@ghilbut",
      "name": "김준형",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@1fY0",
      "name": "강동혁",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@24SO",
      "name": "고종범",
      "category": "개인"
    },
    {
      "url": "https://cheese10yun.github.io/feed.xml",
      "name": "cheese10yun",
      "category": "개인"
    },
    {
      "url": "http://forest71.tistory.com/rss",
      "name": "구자철",
      "category": "개인"
    },
    {
      "url": "https://oraora.tistory.com/rss",
      "name": "FSS",
      "category": "개인"
    },
    {
      "url": "https://mayajuni.github.io/feed.xml",
      "name": "권동준",
      "category": "개인"
    },
    {
      "url": "http://app-developer.tistory.com/rss",
      "name": "김용일",
      "category": "개인"
    },
    {
      "url": "http://seokjun.kr/rss/",
      "name": "김석준",
      "category": "개인"
    },
    {
      "url": "http://www.dokyun.pe.kr/rss",
      "name": "김도균",
      "category": "개인"
    },
    {
      "url": "http://interpiler.com/index.php/feed/",
      "name": "김상훈",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/atom/@@O1Z",
      "name": "김민석",
      "category": "개인"
    },
    {
      "url": "https://dongwoo.blog/feed/",
      "name": "김동우",
      "category": "개인"
    },
    {
      "url": "http://web-front-end.tistory.com/rss",
      "name": "권윤학",
      "category": "개인"
    },
    {
      "url": "https://velopert.com/feed",
      "name": "김민준",
      "category": "개인"
    },
    {
      "url": "https://medium.com/feed/@devholic",
      "name": "강성훈",
      "category": "개인"
    },
    {
      "url": "https://mansoo-sw.blogspot.com/feeds/posts/default",
      "name": "김만수",
      "category": "개인"
    },
    {
      "url": "https://elky84.github.io/feed.xml",
      "name": "엘키",
      "category": "개인"
    },
    {
      "url": "http://thdev.tech/feed.xml",
      "name": "권태환",
      "category": "개인"
    },
    {
      "url": "http://shiren.github.io/feed.xml",
      "name": "김성호",
      "category": "개인"
    },
    {
      "url": "http://blog.seulgi.kim/feeds/posts/default",
      "name": "김슬기",
      "category": "개인"
    },
    {
      "url": "https://kwang82.blogspot.com/feeds/posts/default",
      "name": "김광현",
      "category": "개인"
    },
    {
      "url": "http://sungbine.github.io/feed.xml",
      "name": "김성빈",
      "category": "개인"
    },
    {
      "url": "http://datajournal.kr/feed/",
      "name": "김영우",
      "category": "개인"
    },
    {
      "url": "http://kangmyounghun.blogspot.com/feeds/posts/default",
      "name": "강명훈",
      "category": "개인"
    },
    {
      "url": "http://feeds.feedburner.com/theyearlyprophet/GGGO",
      "name": "구종만",
      "category": "개인"
    },
    {
      "url": "https://b.luavis.kr/feed.xml",
      "name": "강성일",
      "category": "개인"
    },
    {
      "url": "http://minjang.github.io/feed.xml",
      "name": "김민장",
      "category": "개인"
    },
    {
      "url": "http://rss.egloos.com/blog/kwon37xi",
      "name": "권남",
      "category": "개인"
    },
    {
      "url": "http://insanehong.kr/rss.xml",
      "name": "김덕홍",
      "category": "개인"
    },
    {
      "url": "http://sungjk.github.io/feed.xml",
      "name": "김성중",
      "category": "개인"
    },
    {
      "url": "http://danielku.com/atom.xml",
      "name": "구교준",
      "category": "개인"
    },
    {
      "url": "http://martian36.tistory.com/rss",
      "name": "김덕기",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@LOc",
      "name": "고명환",
      "category": "개인"
    },
    {
      "url": "https://medium.com/feed/@shaynekang",
      "name": "강성희",
      "category": "개인"
    },
    {
      "url": "http://j.mearie.org/rss",
      "name": "강성훈",
      "category": "개인"
    },
    {
      "url": "https://01010011.blog/feed/",
      "name": "강병수",
      "category": "개인"
    },
    {
      "url": "https://harfangk.github.io/feed.xml",
      "name": "김봉현",
      "category": "개인"
    },
    {
      "url": "https://hskang9.github.io/feed.xml",
      "name": "강형석",
      "category": "개인"
    },
    {
      "url": "http://babysunmoon.tistory.com/rss",
      "name": "김수로",
      "category": "개인"
    },
    {
      "url": "http://minieetea.com/feed",
      "name": "강미경",
      "category": "개인"
    },
    {
      "url": "http://greemate.tistory.com/rss",
      "name": "김성현",
      "category": "개인"
    },
    {
      "url": "https://brunch.co.kr/rss/@@3Y0",
      "name": "강진우",
      "category": "개인"
    },
    {
      "url": "https://mingrammer.com/index.xml",
      "name": "권민재",
      "category": "개인"
    },
    {
      "url": "https://taetaetae.github.io/index.xml",
      "name": "권태관",
      "category": "개인"
    },
    {
      "url": "http://dokonk.blogspot.com/feeds/posts/default",
      "name": "김도곤",
      "category": "개인"
    },
    {
      "url": "http://keyassist.tistory.com/rss",
      "name": "김영웅",
      "category": "개인"
    },
    {
      "url": "https://rss.blog.naver.com/lbs0718.xml",
      "name": "칡토스의 게임 개발",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/sckim007.xml",
      "name": "김선철",
      "category": "개인"
    },
    {
      "url": "https://nolboo.kim/feed.xml",
      "name": "김놀부",
      "category": "개인"
    },
    {
      "url": "http://rss.egloos.com/blog/isao76",
      "name": "isao의 IT,게임번역소",
      "category": "개인"
    },
    {
      "url": "http://blog.lael.be/feed",
      "name": "Lael's World",
      "category": "개인"
    },
    {
      "url": "http://muzbox.tistory.com/rss",
      "name": "프리웨어 이야기",
      "category": "개인"
    },
    {
      "url": "http://chauchau0.tistory.com/rss",
      "name": "동우리의 블로그",
      "category": "개인"
    },
    {
      "url": "http://www.hatena.co.kr/rss",
      "name": "하테나",
      "category": "개인"
    },
    {
      "url": "http://feeds.feedburner.com/lazion",
      "name": "늑돌이네 라지온",
      "category": "개인"
    },
    {
      "url": "http://bbs.ruliweb.com/news/board/11/rss",
      "name": "루리웹 - 루리웹 리뷰 게시판",
      "category": "게임"
    },
    {
      "url": "https://brunch.co.kr/rss/@@34qN",
      "name": "Reasontobe",
      "category": "개인"
    },
    {
      "url": "http://crazytigerlife.tistory.com/rss",
      "name": "자유로운 생활",
      "category": "개인"
    },
    {
      "url": "http://estima.wordpress.com/feed/",
      "name": "에스티마의 인터넷이야기 EstimaStory.com",
      "category": "개인"
    },
    {
      "url": "http://sacstory.tistory.com/rss",
      "name": "나긋한 개발 - 데비안 리눅스와 프로그램 언어",
      "category": "개인"
    },
    {
      "url": "http://blog.leekyoungil.com/?feed=rss2",
      "name": "Kyoungil's Blog",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/laster40.xml",
      "name": "일상을 여행처럼...",
      "category": "개인"
    },
    {
      "url": "http://khrislog.net/rss",
      "name": "khris'log",
      "category": "개인"
    },
    {
      "url": "http://feedproxy.google.com/rickstrahl",
      "name": "Rick Strahl's Web Log",
      "category": "개인"
    },
    {
      "url": "http://justhackem.wordpress.com/feed/",
      "name": "Just hack'em",
      "category": "개인"
    },
    {
      "url": "http://feeds.feedburner.com/CppTruths",
      "name": "C++ Truths",
      "category": "개인"
    },
    {
      "url": "https://jacking75.github.io/feed.xml",
      "name": "jacking75",
      "category": "개인"
    },
    {
      "url": "http://www.joelonsoftware.com/rss.xml",
      "name": "Joel on Software",
      "category": "개인"
    },
    {
      "url": "http://feeds.feedburner.com/crazytazo",
      "name": "벤자민로그",
      "category": "개인"
    },
    {
      "url": "http://blog.xcoda.net/rss",
      "name": "악보쓰는 프로그래머",
      "category": "개인"
    },
    {
      "url": "http://jeremyko.blogspot.com/feeds/posts/default",
      "name": "쭌안아빠",
      "category": "개인"
    },
    {
      "url": "http://aker.tistory.com/rss",
      "name": "A Gangster World",
      "category": "개인"
    },
    {
      "url": "http://luckyyowu.tistory.com/rss",
      "name": "요우의 내맘대로 블로그",
      "category": "개인"
    },
    {
      "url": "http://blog.gaerae.com/feeds/posts/default",
      "name": "개발자스럽다",
      "category": "큐레이션"
    },
    {
      "url": "http://rss.egloos.com/blog/oniondev",
      "name": "양파개발자 Sw의 블로그입니다^^",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/crisious.xml",
      "name": "Against All Odds.",
      "category": "개인"
    },
    {
      "url": "http://rss.egloos.com/blog/parkpd",
      "name": "박피디의 게임 개발 이야기",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/gal_yong.xml",
      "name": "움직이는 게임서버",
      "category": "개인"
    },
    {
      "url": "http://feeds.feedburner.com/sangwook",
      "name": "이상욱",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/arcangeleri.xml",
      "name": "임철재",
      "category": "개인"
    },
    {
      "url": "https://zzsza.github.io/feed.xml",
      "name": "어쩐지 오늘은",
      "category": "개인"
    },
    {
      "url": "https://oddpoet.net/feed.xml",
      "name": "oddpoet’s étude",
      "category": "개인"
    },
    {
      "url": "http://agile.egloos.com/index.xml",
      "name": "애자일 이야기",
      "category": "개인"
    },
    {
      "url": "https://snutiise.github.io/feed.xml",
      "name": "0x00 - NULL",
      "category": "개인"
    },
    {
      "url": "http://serverdown.tistory.com/rss",
      "name": "퇴근 후 서버다운",
      "category": "개인"
    },
    {
      "url": "https://coolspeed.wordpress.com/feed/",
      "name": "coolspeed",
      "category": "개인"
    },
    {
      "url": "https://perfectacle.github.io/atom.xml",
      "name": "오늘도 끄적끄적",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/sorkelf.xml",
      "name": "dx11 Vanica's Lifelog - 夢が夢で終わらないように",
      "category": "개인"
    },
    {
      "url": "http://arcangeleri.tistory.com/rss",
      "name": "초코사랑",
      "category": "개인"
    },
    {
      "url": "https://www.zerocho.com/api/rss.xml",
      "name": "ZeroCho Blog",
      "category": "개인"
    },
    {
      "url": "http://hybrid0.tumblr.com/rss",
      "name": "Hybrid's Notes",
      "category": "개인"
    },
    {
      "url": "http://rss.egloos.com/blog/Agbird",
      "name": "gimmesilver's blog",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/imays.xml",
      "name": "imays게임엔진개발자",
      "category": "개인"
    },
    {
      "url": "https://rss.blog.naver.com/hurinmon.xml",
      "name": "RSS feed for hurinmon Blog",
      "category": "개인"
    },
    {
      "url": "http://jojoldu.tistory.com/rss",
      "name": "기억보단 기록을",
      "category": "개인"
    },
    {
      "url": "http://westwoodforever.blogspot.com/feeds/posts/default",
      "name": "WestwoodForever's Dev Log",
      "category": "개인"
    },
    {
      "url": "http://java.ihoney.pe.kr/rss",
      "name": "허니몬(Honeymon)의 자바guru",
      "category": "개인"
    },
    {
      "url": "http://honsal.blogspot.kr/feeds/posts/default?alt=rss",
      "name": "Wolf Loves Fox :: 일상",
      "category": "개인"
    },
    {
      "url": "http://kindtis.tistory.com/rss",
      "name": "Game Programmer Life",
      "category": "개인"
    },
    {
      "url": "https://10yearscoder.tistory.com/rss",
      "name": "IT 프리랜서 이야기",
      "category": "개인"
    },
    {
      "url": "https://www.whiteship.me/rss/",
      "name": "Whiteship's Epril",
      "category": "개인"
    },
    {
      "url": "https://megayuchi.wordpress.com/feed/",
      "name": "yuchi's dev",
      "category": "개인"
    },
    {
      "url": "https://joone.net/feed/",
      "name": "만화로 나누는 자유/오픈소스 소프트웨어 이야기",
      "category": "개인"
    },
    {
      "url": "http://hyeonseok.com/rss/",
      "name": "신현석(Hyeonseok Shin)",
      "category": "개인"
    },
    {
      "url": "http://www.sangkon.com/rss/",
      "name": "한상곤 - Sigmadream",
      "category": "개인"
    },
    {
      "url": "https://woolbro.tistory.com/feed/",
      "name": "개발자 울이 노트",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/dlehddus84.xml",
      "name": "즐거운 개발자 :: 네이버  블로그",
      "category": "개인"
    },
    {
      "url": "http://blog.rss.naver.com/kimbeast.xml",
      "name": "황제펭귄의 게임개발이야기 [여기는 한국]",
      "category": "개인"
    },
    {
      "url": "https://engineering.linecorp.com/ko/blog/rss2",
      "name": "LINE ENGINEERING",
      "category": "기업"
    },
    {
      "url": "https://blog.banksalad.com/rss.xml",
      "name": "뱅크샐러드 블로그",
      "category": "기업"
    },
    {
      "url": "http://woowabros.github.io/feed.xml",
      "name": "우아한형제들 기술 블로그",
      "category": "기업"
    },
    {
      "url": "https://meetup.toast.com/rss",
      "name": "TOAST Meetup",
      "category": "기업"
    },
    {
      "url": "https://blog.weirdx.io/feed",
      "name": "이상한모임",
      "category": "기업"
    },
    {
      "url": "https://zuminternet.github.io/feed.xml",
      "name": "ZUM 기술 블로그",
      "category": "기업"
    },
    {
      "url": "http://tech.kakao.com/rss/",
      "name": "tech.kakao.com",
      "category": "기업"
    },
    {
      "url": "https://tech.lezhin.com/rss",
      "name": "레진 기술 블로그",
      "category": "기업"
    },
    {
      "url": "http://feeds.feedburner.com/skpreadme",
      "name": "SK Planet",
      "category": "기업"
    },
    {
      "url": "https://spoqa.github.io/atom.xml",
      "name": "Spoqa tech blog",
      "category": "기업"
    },
    {
      "url": "https://rss.blog.naver.com/teamwaldo.xml",
      "name": "팀 왈도 번역팀",
      "category": "게임"
    },
    {
      "url": "https://wit.nts-corp.com/feed",
      "name": "NTS",
      "category": "기업"
    },
    {
      "url": "https://blog.hanlee.io/rss.xml",
      "name": "이한",
      "category": "개인"
    },
    {
      "url": "https://gracefullight.dev/feed.xml",
      "name": "Gracefullight Web.dev",
      "category": "개인"
    },
    {
      "url": "https://blog.roto.codes/rss/",
      "name": "로토의 블로그",
      "category": "개인"
    },
    {
      "url": "https://highfence.tistory.com/feed",
      "name": "근원님",
      "category": "개인"
    },
    {
      "url": "https://medium.com/feed/@zmag",
      "name": "황의윤",
      "category": "개인"
    },
    {
      "url": "https://hodolman.com/rss",
      "name": "호돌맨",
      "category": "개인"
    },
    {
      "url": "https://wbluke.tistory.com/rss",
      "name": "박우빈",
      "category": "개인"
    },
    {
      "url": "https://v2.velog.io/rss/mdy0102",
      "name": "문다영",
      "category": "개인"
    },
    {
      "url": "https://v2.velog.io/rss/sweet_sumin",
      "name": "유수민",
      "category": "개인"
    },
    {
      "url": "https://v2.velog.io/rss/ahngj96",
      "name": "안건주",
      "category": "개인"
    },
    {
      "url": "https://internet-craft.tistory.com/rss",
      "name": "손현호",
      "category": "개인"
    },
    {
      "url": "https://www.thestartupbible.com/feed",
      "name": "STARTUP BIBLE",
      "category": "개인"
    },
    {
      "url": "https://sonujung.com/rss.xml",
      "name": "Build a Great Product",
      "category": "개인"
    },
    {
      "url": "http://icunow.co.kr/feed/",
      "name": "지금 써보러 갑니다",
      "category": "개인"
    },
    {
      "url": "https://dewberry9.github.io/feed.xml",
      "name": "매거진 입맛",
      "category": "큐레이션"
    },
    {
      "url": "https://yozm.wishket.com/magazine/feed/",
      "name": "요즘 IT",
      "category": "큐레이션"
    },
    {
      "url": "https://medium.com/feed/@coupang-engineering-kr",
      "name": "쿠팡 엔지니어링",
      "category": "기업"
    },
    {
      "url": "https://dev.gmarket.com/rss",
      "name": "지마켓 기술 블로그",
      "category": "기업"
    },
    {
      "url": "https://blog.dramancompany.com/feed/",
      "name": "리멤버 (드라마 앤 컴퍼니)",
      "category": "기업"
    },
    {
      "url": "https://techblogposts.com/rss.xml",
      "name": "Tech Blog Posts",
      "category": "큐레이션"
    },
    {
      "url": "https://kimchihill.com/feed/",
      "name": "Kimchi hill",
      "category": "큐레이션"
    },
    {
      "url": "https://hudi.blog/rss.xml",
      "name": "Hudi.blog",
      "category": "개인"
    },
    {
      "url": "https://blog.toss.im/rss.xml",
      "name": "토스",
      "category": "기업"
    },
    {
      "name": "모나미",
      "url": "https://v2.velog.io/rss/monami",
      "category": "개인"
    },
    {
      "name": "황인서 (체커)",
      "url": "https://hislogs.com/rss.xml",
      "category": "개인"
    }
  ]
}

### Rss Create Multi

POST {{host}}/Rss/Multi
Content-Type: application/json

{
    "Datas": [
      {
      "name": "모나미",
      "url": "https://v2.velog.io/rss/monami",
      "category": "개인"
      }
    ]
}


### Rss Create

POST {{host}}/Rss
Content-Type: application/json

{
    "Data": {
        "Url": "https://internet-craft.tistory.com/rss",
        "Name": "손현호",
        "category": "개인"
    }
}

### Rss Get

GET {{host}}/Rss/5f5a25cc6e6fbaf1a5e7ccca

### Rss Update

PUT {{host}}/Rss/5f5a25cc6e6fbaf1a5e7ccca
Content-Type: application/json

{
    "Data": {
        "Url": "http://elky84.github.io/feed.xml",
        "Name": "Elky Essay"
    }
}

### Rss Delete

DELETE {{host}}/Rss/5f5a25cc6e6fbaf1a5e7ccca

